#=================================================
# Description: Build ubports using GitHub Actions
# Lisence: MIT
# Author: 0312birdzhang
# Credit: https://github.com/P3TERX/Actions-OpenWrt
#=================================================

name: Build Ubports

on: 
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        android-tools-mkbootimg bc build-essential \
        ca-certificates curl git kmod libssl-dev libtinfo5 python2 \
        unzip wget xz-utils -y --no-install-recommends
        sudo ln -sf python2.7 /usr/bin/python

    - name: Build
      run: |
        chmod +x build.sh
        chmod +x build/*.sh
        ./build.sh
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: device_davinci.tar.xz
        path: /home/runner/work/ubports-ci/ubports-ci/out/device_davinci.tar.xz